### ISSUE TITLE
Core server on DOCKER not starting

### ISSUE THREAD

**Issue by cector2019** [intrigueio/intrigue-core#100]
Hi,

I installed docker at my Macbook Pro 10.14.6 and used below commands:

IMAGE="intrigueio/intrigue-core:latest"
docker pull $IMAGE && \
docker run -e LANG=C.UTF-8 -p 0.0.0.0:7777:7777 -i -t $IMAGE 

And getting below error everytime:

> docker run -e LANG=C.UTF-8 -p 0.0.0.0:7777:7777 -i -t $IMAGE
latest: Pulling from intrigueio/intrigue-core
Digest: sha256:45ac19f9a217e29134e2adbd821b4de7471d410cdf6c4ddcb084930c511ba654
Status: Image is up to date for intrigueio/intrigue-core:latest
docker.io/intrigueio/intrigue-core:latest
   _________________________________________________________________________________________________________________
  /                                                                                                                 \
  |                                            Welcome to Intrigue Core!                                            |
  |                                                                                                                 |
  |   To start/restart the Core server on DOCKER, run: /core/util/control.sh stop && /core/util/control.sh start    |
  |            To start/restart the Core server on EC2,    run: /home/ubuntu/core/util/control.sh start             |
  |                                                                                                                 |
  |                 Please file bugs & requests: https://github.com/intrigueio/intrigue-core/issues                 |
  |                                                                                                                 |
  |                               Other comments? Questions? Email hello@intrigue.io.                               |
  \______________________________________________________________________________________________________________ '\
                                                                                                             ()    \\
                                                                                                               O    \\  .
                                                                                                                 o  |\\/|
                                                                                                                    / " '\
                                                                                                                    . .   .
                                                                                                                   /    ) |
                                                                                                                  '  _.'  |
                                                                                                                  '-'/    \

[+] Restarting Postgres...
 * Restarting PostgreSQL 11 database server                                                                                 [ OK ] 
[+] Restarting Redis...
Stopping redis-server: redis-server.
Starting redis-server: redis-server.
[+] Restarting Intrigue...
/core/util/docker_entry.sh: line 11: /core/util/control.sh: No such file or directory
[+] Tailing sidekiq.log...
tail: cannot open '/core/log/sidekiq*.log' for reading: No such file or directory
tail: no files remaining

Please assist me how can I solve this issue.

Thank you.

**Comment by jcran** [comment]
Looks like this happened as part of the move to sidekiq 6. working on it now, thanks for filing an issue.

**Comment by cector2019** [comment]
Please update here, when issue will be fixed. So, I download again Intrigue in Docker.

Thank you.

**Comment by jcran** [comment]
Updated image is now available and moves services underneath a proper process manager. Please re-open if you have any troubles.

**Comment by cector2019** [comment]
Thanks
