### ISSUE TITLE
You're seeing this error because you have enabled the show_exceptions setting

### ISSUE THREAD

**Issue by cector2019** [intrigueio/intrigue-core#101]
Now, I am facing new issue after start the scanning below:

I also found same error below for Enumerate an FTP server.

RuntimeError at /Default/interactive/single
Unable to create entity, check your parameters: 98.137.246.7 Uri!
		file: results.rb location: block in <class:IntrigueApp> line: 137

BACKTRACE
(expand)
JUMP TO: GET POST COOKIES ENV

		/core/app/routes/results.rb in block in <class:IntrigueApp>
	137.	        raise "Unable to create entity, check your parameters: #{entity_name} #{entity_type}!"

Variable | Value
-- | --
attrib_name | "98.137.246.7"
auto_enrich | "on"
depth | "1"
entity_type | "Uri"
machine | "org_asset_discovery_active"
option_ssrf_target_uri | "http://localhost:55555"
option_target_environment | "all"
task | "vuln/ssrf_proxy_host_header"

Variable | Value
-- | --
security_level | "0"
PHPSESSID | "ed3a6be64533c0f4c03391d520d044ca"
rack.session | "BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTRkZTlhYTU1MmFiMDE5NDExNmQw\nYWVhZjY5ZTFjODEwNDgxMTQ3MzVkMGExYmJiODc2MzVlN2FiNGY4ZmYyZWUG\nOwBGSSIJY3NyZgY7AEZJIjFwVmg1L2twQW5oaGx3VU9jV2Jhb2pKeVJrRXFy\nQ0kwMnRUVDdQS29DNzdBPQY7AEZJIg10cmFja2luZwY7AEZ7BkkiFEhUVFBf\nVVNFUl9BR0VOVAY7AFRJIi05NTkxNjIwZDEyYzk1MzBmYzBlNjU2YTIyYjk0\nMTUwOGRkZmMyZWM2BjsARg==\n--daa7e59c8bb15830ea6a4c8244e2ba4d9f6cc47d"

Variable | Value
-- | --
CONTENT_LENGTH | 932
CONTENT_TYPE | multipart/form-data; boundary=----WebKitFormBoundary5qKykhSkFEZmCAtY
GATEWAY_INTERFACE | CGI/1.2
HTTP_ACCEPT | text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
HTTP_ACCEPT_ENCODING | gzip, deflate, br
HTTP_ACCEPT_LANGUAGE | en-US,en;q=0.9
HTTP_AUTHORIZATION | Basic aW50cmlndWU6eGtuZWNqZmJ6Y2w=
HTTP_CACHE_CONTROL | max-age=0
HTTP_CONNECTION | keep-alive
HTTP_COOKIE | security_level=0; PHPSESSID=ed3a6be64533c0f4c03391d520d044ca; rack.session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTRkZTlhYTU1MmFiMDE5NDExNmQw%0AYWVhZjY5ZTFjODEwNDgxMTQ3MzVkMGExYmJiODc2MzVlN2FiNGY4ZmYyZWUG%0AOwBGSSIJY3NyZgY7AEZJIjFwVmg1L2twQW5oaGx3VU9jV2Jhb2pKeVJrRXFy%0AQ0kwMnRUVDdQS29DNzdBPQY7AEZJIg10cmFja2luZwY7AEZ7BkkiFEhUVFBf%0AVVNFUl9BR0VOVAY7AFRJIi05NTkxNjIwZDEyYzk1MzBmYzBlNjU2YTIyYjk0%0AMTUwOGRkZmMyZWM2BjsARg%3D%3D%0A--daa7e59c8bb15830ea6a4c8244e2ba4d9f6cc47d
HTTP_HOST | localhost:7777
HTTP_ORIGIN | http://localhost:7777
HTTP_REFERER | http://localhost:7777/Default/start
HTTP_SEC_FETCH_MODE | navigate
HTTP_SEC_FETCH_SITE | same-origin
HTTP_SEC_FETCH_USER | ?1
HTTP_UPGRADE_INSECURE_REQUESTS | 1
HTTP_USER_AGENT | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
HTTP_VERSION | HTTP/1.1
PATH_INFO | /Default/interactive/single
QUERY_STRING |  
REMOTE_ADDR | 172.17.0.1
REMOTE_USER | intrigue
REQUEST_METHOD | POST
REQUEST_PATH | /Default/interactive/single
REQUEST_URI | /Default/interactive/single
SCRIPT_NAME |  
SERVER_NAME | localhost
SERVER_PORT | 7777
SERVER_PROTOCOL | HTTP/1.1
SERVER_SOFTWARE | puma 4.2.0 Distant Airhorns
puma.config | #<Puma::Configuration:0x000055bd5c735d10 @options=#<Puma::UserFileDefaultOptions:0x000055bd5c735680 @user_options={:binds=>["tcp://0.0.0.0:7777"], :environment=>"development"}, @file_options={:config_files=>["/core/config/puma.rb"], :environment=>"development", :daemon=>false, :binds=>["tcp://127.0.0.1:7777"]}, @default_options={:min_threads=>0, :max_threads=>16, :log_requests=>false, :debug=>false, :binds=>["tcp://0.0.0.0:9292"], :workers=>0, :daemon=>false, :mode=>:http, :worker_timeout=>60, :worker_boot_timeout=>60, :worker_shutdown_timeout=>30, :remote_address=>:socket, :tag=>"core", :environment=>"development", :rackup=>"config.ru", :logger=>#<IO:<STDOUT>>, :persistent_timeout=>20, :first_data_timeout=>30, :raise_exception_on_sigterm=>true}>, @plugins=#<Puma::PluginLoader:0x000055bd5c7355e0 @instances=[]>, @user_dsl=#<Puma::DSL:0x000055bd5c735158 @config=#<Puma::Configuration:0x000055bd5c735d10 ...>, @options={:binds=>["tcp://0.0.0.0:7777"], :environment=>"development"}, @plugins=[]>, @file_dsl=#<Puma::DSL:0x000055bd5c737b10 @config=#<Puma::Configuration:0x000055bd5c735d10 ...>, @options={:config_files=>["/core/config/puma.rb"], :environment=>"development", :daemon=>false, :binds=>["tcp://127.0.0.1:7777"]}, @plugins=[], @path="/core/config/puma.rb">, @default_dsl=#<Puma::DSL:0x000055bd5c73ecf8 @config=#<Puma::Configuration:0x000055bd5c735d10 ...>, @options={:min_threads=>0, :max_threads=>16, :log_requests=>false, :debug=>false, :binds=>["tcp://0.0.0.0:9292"], :workers=>0, :daemon=>false, :mode=>:http, :worker_timeout=>60, :worker_boot_timeout=>60, :worker_shutdown_timeout=>30, :remote_address=>:socket, :tag=>"core", :environment=>"development", :rackup=>"config.ru", :logger=>#<IO:<STDOUT>>, :persistent_timeout=>20, :first_data_timeout=>30, :raise_exception_on_sigterm=>true}, @plugins=[]>>
puma.request_body_wait | 0
puma.socket | #<TCPSocket:fd 17, AF_INET, 172.17.0.2, 7777>
rack.after_reply | []
rack.errors | #<Object:0x000055bd5d05c2e0>
rack.hijack | #<Puma::Client:0x3f93d512aff4 @ready=true>
rack.hijack? | true
rack.input | #<StringIO:0x00007f27aa255570>
rack.logger | #<Rack::NullLogger:0x000055bd5e1cca70 @app=#<Rack::Session::Cookie:0x000055bd5e1ccf20 @secrets=["a48da31a163e36197fd63fade56e279c17323fe30a2a29127415a1d7b2faa7560d5a257edcb1362c975424d061207fab2881b095bf0c9218d7607480561f58fd"], @hmac=OpenSSL::Digest::SHA1, @coder=#<Rack::Session::Cookie::Base64::Marshal:0x000055bd5e1ccd18>, @app=#<Rack::Protection::FrameOptions:0x000055bd5e1cd240 @app=#<Rack::Protection::HttpOrigin:0x000055bd5e1cd920 @app=#<Rack::Protection::IPSpoofing:0x000055bd5e1cddf8 @app=#<Rack::Protection::JsonCsrf:0x000055bd5e1ce118 @app=#<Rack::Protection::PathTraversal:0x000055bd5e1ce320 @app=#<Rack::Protection::RemoteToken:0x000055bd5e1ce4b0 @app=#<Rack::Protection::SessionHijacking:0x000055bd5e1ce7a8 @app=#<Rack::Protection::XSSHeader:0x000055bd5e1ce8e8 @app=#<Rack::Auth::Basic:0x000055bd5e028570 @app=#<IntrigueApp:0x000055bd5e029b78 @default_layout=:layout, @preferred_extension=nil, @app=nil, @template_cache=#<Tilt::Cache:0x000055bd5e029b50 @cache={}>>, @realm="Restricted", @authenticator=#<Proc:0x000055bd5de63618@/core/core.rb:142>>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :xss_mode=>:block, :nosniff=>true, :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>false}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :tracking_key=>:tracking, :encrypt_tracking=>true, :track=>["HTTP_USER_AGENT"], :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>false}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :authenticity_param=>"authenticity_token", :allow_if=>nil, :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>false}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>false}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :allow_if=>nil, :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>false}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>false}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :allow_if=>nil, :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>false}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :frame_options=>:sameorigin, :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>false}, @frame_options="SAMEORIGIN">, @default_options={:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :sidbits=>128, :secure_random=>SecureRandom, :secret=>"a48da31a163e36197fd63fade56e279c17323fe30a2a29127415a1d7b2faa7560d5a257edcb1362c975424d061207fab2881b095bf0c9218d7607480561f58fd", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x000055bd5e1ccd18>}, @key="rack.session", @cookie_only=true, @sidbits=128, @sid_secure=SecureRandom, @sid_length=32>>
rack.multiprocess | false
rack.multithread | true
rack.request.cookie_hash | {"security_level"=>"0", "PHPSESSID"=>"ed3a6be64533c0f4c03391d520d044ca", "rack.session"=>"BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTRkZTlhYTU1MmFiMDE5NDExNmQw\nYWVhZjY5ZTFjODEwNDgxMTQ3MzVkMGExYmJiODc2MzVlN2FiNGY4ZmYyZWUG\nOwBGSSIJY3NyZgY7AEZJIjFwVmg1L2twQW5oaGx3VU9jV2Jhb2pKeVJrRXFy\nQ0kwMnRUVDdQS29DNzdBPQY7AEZJIg10cmFja2luZwY7AEZ7BkkiFEhUVFBf\nVVNFUl9BR0VOVAY7AFRJIi05NTkxNjIwZDEyYzk1MzBmYzBlNjU2YTIyYjk0\nMTUwOGRkZmMyZWM2BjsARg==\n--daa7e59c8bb15830ea6a4c8244e2ba4d9f6cc47d"}
rack.request.cookie_string | security_level=0; PHPSESSID=ed3a6be64533c0f4c03391d520d044ca; rack.session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTRkZTlhYTU1MmFiMDE5NDExNmQw%0AYWVhZjY5ZTFjODEwNDgxMTQ3MzVkMGExYmJiODc2MzVlN2FiNGY4ZmYyZWUG%0AOwBGSSIJY3NyZgY7AEZJIjFwVmg1L2twQW5oaGx3VU9jV2Jhb2pKeVJrRXFy%0AQ0kwMnRUVDdQS29DNzdBPQY7AEZJIg10cmFja2luZwY7AEZ7BkkiFEhUVFBf%0AVVNFUl9BR0VOVAY7AFRJIi05NTkxNjIwZDEyYzk1MzBmYzBlNjU2YTIyYjk0%0AMTUwOGRkZmMyZWM2BjsARg%3D%3D%0A--daa7e59c8bb15830ea6a4c8244e2ba4d9f6cc47d
rack.request.form_hash | {"task"=>"vuln/ssrf_proxy_host_header", "entity_type"=>"Uri", "attrib_name"=>"98.137.246.7", "option_ssrf_target_uri"=>"http://localhost:55555", "option_target_environment"=>"all", "machine"=>"org_asset_discovery_active", "depth"=>"1", "auto_enrich"=>"on"}
rack.request.form_input | #<StringIO:0x00007f27aa255570>
rack.request.query_hash | {}
rack.request.query_string |  
rack.run_once | false
rack.session | {"session_id"=>"4de9aa552ab0194116d0aeaf69e1c81048114735d0a1bbb87635e7ab4f8ff2ee", "csrf"=>"pVh5/kpAnhhlwUOcWbaojJyRkEqrCI02tTT7PKoC77A=", "tracking"=>{"HTTP_USER_AGENT"=>"9591620d12c9530fc0e656a22b941508ddfc2ec6"}}
rack.session.options | {:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :sidbits=>128, :secure_random=>SecureRandom, :secret=>"a48da31a163e36197fd63fade56e279c17323fe30a2a29127415a1d7b2faa7560d5a257edcb1362c975424d061207fab2881b095bf0c9218d7607480561f58fd", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x000055bd5e1ccd18>}
rack.session.unpacked_cookie_data | {"session_id"=>"4de9aa552ab0194116d0aeaf69e1c81048114735d0a1bbb87635e7ab4f8ff2ee", "csrf"=>"pVh5/kpAnhhlwUOcWbaojJyRkEqrCI02tTT7PKoC77A=", "tracking"=>{"HTTP_USER_AGENT"=>"9591620d12c9530fc0e656a22b941508ddfc2ec6"}}
rack.tempfiles | []
rack.url_scheme | http
rack.version | [1, 3]
sinatra.accept | [#<Sinatra::Request::AcceptEntry:0x00007f27aa2883f8 @entry="application/signed-exchange;v=b3", @type="application/signed-exchange", @params={"v"=>"b3"}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00007f27aa288df8 @entry="text/html", @type="text/html", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00007f27aa288cb8 @entry="application/xhtml+xml", @type="application/xhtml+xml", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00007f27aa2888f8 @entry="image/webp", @type="image/webp", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00007f27aa2887b8 @entry="image/apng", @type="image/apng", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00007f27aa288b78 @entry="application/xml;q=0.9", @type="application/xml", @params={}, @q=0.9>, #<Sinatra::Request::AcceptEntry:0x00007f27aa288678 @entry="*/*;q=0.8", @type="*/*", @params={}, @q=0.8>]
sinatra.error | #<RuntimeError: Unable to create entity, check your parameters: 98.137.246.7 Uri!>
sinatra.error.params | {"task"=>"vuln/ssrf_proxy_host_header", "entity_type"=>"Uri", "attrib_name"=>"98.137.246.7", "option_ssrf_target_uri"=>"http://localhost:55555", "option_target_environment"=>"all", "machine"=>"org_asset_discovery_active", "depth"=>"1", "auto_enrich"=>"on", "project"=>"Default"}
sinatra.route | POST /:project/interactive/single/?

You're seeing this error because you have enabled the show_exceptions setting.

Please assist me how can I solve this issue.

**Comment by cector2019** [comment]
Any update please.

**Comment by jcran** [comment]
Essentially you were feeding the system input it couldn't understand and it was throwing an uncaught exception. All Uri entities should begin with http:// or https://  - if you adjust your input, this will resolve the issue. 

Also, as an additional effort to help in situations where users are new to the system, we will show a flash message that links to a new page that gives some examples of input that you can pass to the system. You can also reach this page through the System -> Entities menu. 

Screenie of this new page:
![image](https://user-images.githubusercontent.com/76854/66486870-0229ab00-ea71-11e9-8817-0fa395e009be.png)

**Comment by jcran** [comment]
This should resolve the issue for you, please open a new ticket for any follow-on issues you experience.
