### ISSUE TITLE
Scope issues

### ISSUE THREAD

**Issue by bugf1nd3r** [intrigueio/intrigue-core#112]
Hi,

If I want to access an organization with scope *.domain.com and If I try to create project for the same in core with the iteration of around 4-5. Then Intrigue creates lots of tasks on third party websites like Google/CloudFront etc.. Which is not required.

Can we have option to run all discovery or other tasks only related to domain and subdomain.. so that for every project we can avoid running resources and tasks for Google/Cloudfront etc third part services?

Currently, If I add a project with *.domain.com, I can see lots of tasks queued for

1) Google
2) CloudFront
3) Jira
4) demo1 etc.. 
on their domain

We need to have option of to run tasks on inscope items only

**Comment by jcran** [comment]
User was using the "run every task" machine, which has since been disabled. If you're still running into this and using the discovery_active or discovery_passive tasks, please re-open.
