### ISSUE TITLE
SQL errors selecting any CPE link under %project%/analysis/fingerprints

### ISSUE THREAD

**Issue by JoeUser47** [intrigueio/intrigue-core#113]
SQL error page returns when clicking any of the CPE links on a project page fingerprints. ( http://localhost:7777/%project%/analysis/fingerprints )

Return is: `
Sequel::DatabaseError at /***project_name***/entities
PG::UndefinedFunction: ERROR: operator does not exist: jsonb ~~* text LINE 1: ...ERE (("entities"."project_id" = 2) AND ("details" ILIKE '%cp... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

    file: postgres.rb location: exec line: 156 
`

`rack.request.query_string 	
search_string=details:cpe:2.3:s:cloudflare:cloudflare::`

`sinatra.error 	
#<Sequel::DatabaseError: PG::UndefinedFunction: ERROR: operator does not exist: jsonb ~~* text LINE 1: ...ERE (("entities"."project_id" = 2) AND ("details" ILIKE '%cp... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. >
sinatra.error.params 	
{"search_string"=>"details:cpe:2.3:s:cloudflare:cloudflare::", "project"=>"***projectname***"}
`

**Comment by JoeUser47** [comment]
Attaching full saved page of error, hope it helps. Happy to upload any log needed, just let me know where it is.


[Sequel__DatabaseError at _TARGET_REDACTED_entities.zip](https://github.com/intrigueio/intrigue-core/files/4362828/Sequel__DatabaseError.at._TARGET_REDACTED_entities.zip)

**Comment by jcran** [comment]
Just a note that this is currently blocked on an updated (and in progress!) UX.
