### ISSUE TITLE
some ssl error

### ISSUE THREAD

**Issue by xxnbyy** [intrigueio/intrigue-core#114]
when i start the docker ,i can't visit the web from https://127.0.0.1:7777,and when i curl the address,it return follow
root@kali:~/Desktop# curl -v https://127.0.0.1:7777
*   Trying 127.0.0.1:7777...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 7777 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

I'm use kali linux 2020.1 ,and the openssl version is OpenSSL 1.1.1d  10 Sep 2019

---------------------------------------------------------------------------------------
i change the openssl to 1.1.1 and it still not work

**Comment by jcran** [comment]
Is the image serving ssl? Have you tried accessing it on http? Please provide any more information you can.

**Comment by xxnbyy** [comment]
I have try to visit the web on http, and it can't work still

**Comment by jcran** [comment]
Unable to repro
