### ISSUE TITLE
Can't download latest cve json from the NVD in China

### ISSUE THREAD

**Issue by xxnbyy** [intrigueio/intrigue-core#115]
I can't get the latest cve json from the nvd in China sometime,it return 403 ,is there other solutions for us?
![image](https://user-images.githubusercontent.com/20261647/76043534-ca2c8280-5f92-11ea-8b9f-3462804c7cb5.png)

when the process stop there it even can't create a password to login

**Comment by jcran** [comment]
Sorry for the delay. The current solution for this is simply to adjust the download and roll your own image. You can find the code that downloads the NVD data in data/get_latest.sh. remove or comment the lines that do this download and roll the image according to the instructions here: http://core.intrigue.io/2017/03/07/using-intrigue-core-with-docker/

Please re-open if this doesnt address the issue for you.
