### ISSUE TITLE
pg_ctl: directory "/data/postgresql" is not a database cluster directory

### ISSUE THREAD

**Issue by praseudo** [intrigueio/intrigue-core#129]
While trying to install it in one of my DigitalOcean Droplet in Ubuntu 18.04 version.

I've followed the exact same steps which was shown in the below link:
https://core.intrigue.io/2020/02/19/getting-started-on-digital-ocean/

Am facing the below error while setting up.

<img width="759" alt="error1" src="https://user-images.githubusercontent.com/38332922/81064122-bcde3680-8ef6-11ea-9bf1-2431daa1cb62.png">

Can anyone please help me out on the fix ?

**Comment by jcran** [comment]
We've had a couple reports like this recently. It may be related to the upgrade to postgres 12 as part of 3.7.1, and definitely seems to be related to the /data directory mapping. Will dig in and reply when a solution is available.

**Comment by jcran** [comment]
Believe this is the same issue as #128, currently working on a fix. ETA today.

**Comment by jcran** [comment]
Fix is up on master (removes installation of postgres 10, while staying on the base image of Ubuntu 18.04), and standalone image is currently rebuilding, eta 30min. Verified by building locally and the service is up and running as expected on startup.
