### ISSUE TITLE
Error saving gitrob results on AWS EC2 AMI

### ISSUE THREAD

**Issue by HollywoodMarks** [intrigueio/intrigue-core#130]
I've recently built a new server using the AWS EC2 AMI, and updated the configs.
The issue occurs when running the gitrob Task.  It looks like there may be an issue writing the output file, but I don't see any logging to help troubleshoot.

**Screen output:**
[_] Options: []
[_] Starting task run at 2020-05-05 15:01:10 UTC!
[_] Starting Gitrob on xxxxxxxxxxxxxx, saving to /tmp/gitrob_463817301270.json!
[_] Gitrob finished on xxxxxxxxxxxxxx!
[E] No such file: /tmp/gitrob_463817301270.json
[E] No output, failing
[_] Task run finished at 2020-05-05 15:01:10 UTC!
[_] Not an enrichment task, skipping machine generation
[_] Task complete. Ship it!

**Comment by jcran** [comment]
Thanks for the report, looking into it.

**Comment by jcran** [comment]
can you verify that gitrob is on the box, and able to be run in the default path using `gitrob -h`? Wondering if there's something wrong at install time. If installed correctly, it should give you: 

```
jcran core jcran [20200505]$ gitrob -h
Usage of gitrob:
  -bind-address string
    	Address to bind web server to (default "127.0.0.1")
  -commit-depth int
    	Number of repository commits to process (default 500)
  -debug
    	Print debugging information
  -github-access-token string
    	GitHub access token to use for API requests
  -load string
    	Load session file
  -no-expand-orgs
    	Don't add members to targets when processing organizations
  -port int
    	Port to run web server on (default 9393)
  -save string
    	Save session to file
  -silent
    	Suppress all output except for errors
  -threads int
    	Number of concurrent threads (default number of logical CPUs)```

**Comment by HollywoodMarks** [comment]
Good point, I wasn't sure how it was being invoked.  
No, it does not run from the command line.

~/core$ gitrob -h
gitrob: command not found

**Comment by jcran** [comment]
Excellent, thanks for the feedback. Digging into this to see why it's not being installed properly.

**Comment by HollywoodMarks** [comment]
I did some troubleshooting today.  Try to build again and received the following error:
../../../gin-gonic/gin/context.go:778:91: undefined: http.SameSite
../../../gin-gonic/gin/context.go:788:11: unknown field 'SameSite' in struct literal of type http.Cookie

Looks like someone else filed an issue for it:
https://github.com/michenriksen/gitrob/issues/197

**Comment by HollywoodMarks** [comment]
Found the issue:
SameSite requires Go 1.11,  and 1.10 was installed
This is because it sets the SameSite attribute on the session cookie for additional security, but that attribute is only supported in 1.11 onwards.
https://github.com/alexedwards/scs/issues/60

Updated Go: https://github.com/golang/go/wiki/Ubuntu
$ sudo add-apt-repository ppa:longsleep/golang-backports
$ sudo apt update

Found another dependency issue:
[-] Dependency zip not found !

#Install zip
$ sudo apt install zip

#Installed gitrob
$ go get github.com/michenriksen/gitrob

**Comment by jcran** [comment]
This might resolve it? https://github.com/intrigueio/intrigue-core/compare/5134d253de08...7ba209e4fc77#

**Comment by jcran** [comment]
This should do the trick. https://github.com/intrigueio/intrigue-core/pull/244
