### ISSUE TITLE
Capability to provide the username and password for the official Docker Image

### ISSUE THREAD

**Issue by hiddengearz** [intrigueio/intrigue-core#131]
Hello,

I recently started using intrigue-core and I'm loving it so far, great job!

I was wondering for users that use docker-compose with the official docker image to manage their docker deployments is is possible to expose a username and password variable? Similar to what is done with the docker-compose.yml file to build the image? 

https://github.com/intrigueio/intrigue-core/blob/66141052afb7196bed5bf12082c4646ed897741c/docker-compose.yml#L31

Here is an example of what I'm trying to do, I'm not sure how normal it is to manage images/containers this way but I've found it easier this way when you have a large amount that interact with one another.

docker-compose.yml: 
```
...
  intrigueio:
    image: "intrigueio/intrigue-core:latest"
    restart: always
    ports:
      - "7777"
    environment:
      - LANG=C.UTF-8
      - DB_USER="username"
      - DB_PASS='password'
    labels:
      - traefik.enable=true
      - traefik.backend=subdomain
      - traefik.frontend.rule=Host:subdomain.mydomain.com
      - traefik.docker.network=web
      - traefik.default.protocol=http
      - traefik.port=80
    networks:
      - web
    depends_on:
      - proxy
    volumes:
      -  /home/myuser/intrigue-core-data:/data```

**Comment by jcran** [comment]
Thanks! 

Just to make sure i understand, you'd like the ability to specify the core (system) password at runtime via docker argument / env variable? Presumably so you don't have to grab it out of the log?

**Comment by hiddengearz** [comment]
Correct, currently whenever I do docker-compose down/up or restart my server I have to go to the logs to get the username/password.

On May 8, 2020, at 12:52 AM, Jonathan Cran <notifications@github.com> wrote:

﻿

Thanks!

Just to make sure i understand, you'd like the ability to specify the core (system) password at runtime via docker argument / env variable? Presumably so you don't have to grab it out of the log?

**Comment by jcran** [comment]
Quick update here, we're going to action this, but want to move the config file to dot notation at the same time. Will be a bit but this is near the top of the list. Join our slack (shoot email to hello-at-intrigue.io) if you want more context.
