### ISSUE TITLE
Send to Local ElasticSearch

### ISSUE THREAD

**Issue by uBadRequest** [intrigueio/intrigue-core#155]
Is it possible to have a handler for exporting data to a local elasticsearch? I'd rather just send the logs to my local instance then setup a new one in AWS.

**Comment by jcran** [comment]
Thanks for the report, should be very similar to what we're currently doing for AWS, will action this.

**Comment by jcran** [comment]
Realized that if you're using this in the docker setup, elasticsearch won't be at 127.0.0.1, so that's not a super sensible default. Any more info you can provide on how this will be used? Thinking it might be prudent to have a modal that asks you to provide IP/creds.

**Comment by uBadRequest** [comment]
I guess I could just edit the docker compose file to create a reverse ssh tunnel or I think I can use the host flag an let the container use the hosts networking stack. Currently mine isn’t configured to use authentication...

**Comment by jcran** [comment]
Cool, let me know what works for you, it'd be good to do a writeup on it. Thanks!!

**Comment by jcran** [comment]
Calling this done for now.
