### ISSUE TITLE
Add task for wayback machine

### ISSUE THREAD

**Issue by jcran** [intrigueio/intrigue-core#156]
Wayback machine looks like it could provide some good intel, create a task (or set of tasks) that pulls data. 

Ideas: 
 - https://medium.com/@ghostlulzhacks/wayback-machine-e678a3567ec
 - https://medium.com/@zseano/its-all-in-the-detail-email-leak-account-takeover-thanks-to-waybackmachine-extensive-4be365580dd7
 - https://pentester.land/podcast/2019/03/01/the-bug-hunter-podcast-02.html
 - https://www.hahwul.com/2020/03/recon-with-waybackmachine-for-bugbounty.html

**Comment by uBadRequest** [comment]
I would suggest taking at a look at https://github.com/lc/gau

**Comment by jcran** [comment]
Implemented by @m-q-t https://github.com/intrigueio/intrigue-core/blob/develop/lib/tasks/search_wayback_machine.rb
