### ISSUE TITLE
TypeError at /system/config/handlers

### ISSUE THREAD

**Issue by l0Op3r** [intrigueio/intrigue-core#173]
Throws error message when attempting to visit the config handlers page.

This was found in the latest docker image in docker hub.

<img width="1165" alt="Screen Shot 2020-08-21 at 16 15 24" src="https://user-images.githubusercontent.com/4775191/90942229-b900f200-e3c9-11ea-8e94-d4bc28bd1263.png">

**Comment by an0th3rhuman** [comment]
Got the same error too. Used latest docker image

**Comment by jcran** [comment]
Fixing this by removing handler configuration in the legacy UI for now.
