### ISSUE TITLE
Can Intrigue-core be installed on Kali Linux?

### ISSUE THREAD

**Issue by walldoggydogg911** [intrigueio/intrigue-core#174]
I can't seem to find any indication that Intrigue-core can be installed in Kali via python.  Is this not possible? 

I see installs on Docker, EC2, Digital Ocean etc, but not for Kali. 

Any help would be great.  Thanks.

**Comment by walldoggydogg911** [comment]
I was able to install docker, and run the docker one liner successfully, generating a username and password, but after the download, i can't access the interface. I am trying 127.0.0.1:7777, but the firefox browser just hangs. 
![Intrigue_browswer](https://user-images.githubusercontent.com/54041238/90992521-4f761480-e57e-11ea-8e60-26f0b19169b9.png)
![Intrigue_Download](https://user-images.githubusercontent.com/54041238/90992592-ca3f2f80-e57e-11ea-895d-a7976dcab25b.png)

**Comment by walldoggydogg911** [comment]
Nevermind.  I found out i needed to make it https://127.0.00.1:7777.  Left out the "s"

Sorry guys.  I'm still a NooB.

**Comment by JoeUser47** [comment]
Don't be sorry, join the slack anyway, great group to learn with together.
