### ISSUE TITLE
Error when starting the image

### ISSUE THREAD

**Issue by JaderKb** [intrigueio/intrigue-core#203]
The following error appears on the screen after run:
docker pull $IMAGE && docker run -e LANG=C.UTF-8 --memory=8g -v ~/intrigue-core-data:/data -p 0.0.0.0:7777:7777 -it $IMAGE

latest: Pulling from intrigueio/intrigue-core
Digest: sha256:3521659d8e009b0dae48422119811a8ba353d927cea63cf9e7cf18a076916458
Status: Image is up to date for intrigueio/intrigue-core:latest
docker.io/intrigueio/intrigue-core:latest
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/****************************************************************************************/
/*                              Welcome to Intrigue Core!                               */
/*                                                                                      */
/* Please file bugs & requests here: https://github.com/intrigueio/intrigue-core/issues */
/*                                                                                      */
/*                 Other comments? Questions? Email hello@intrigue.io.                  */
/****************************************************************************************/
[+] Starting postgres
 * Starting PostgreSQL 12 database server                                                                                              **###  *** Error: /usr/lib/postgresql/12/bin/pg_ctl /usr/lib/postgresql/12/bin/pg_ctl start -D /data/postgres -l /var/log/postgresql/postgresql-12-main.log -s -o  -c config_file="/etc/postgresql/12/main/postgresql.conf"  exited with status 1: 
pg_ctl: directory "/data/postgres" is not a database cluster directory****
                                                                                                                                [fail]
createuser: error: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
createdb: error: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
[+] Starting redis
Starting redis-server: redis-server.
[+] Migrating DB for Intrigue Standalone
rake aborted!
Sequel::DatabaseConnectionError: PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

**Comment by JoeUser47** [comment]
I've had issues running with docker engine that came with distro, but was successful after installing from https://docs.docker.com/engine/install/ . What OS/Distro are you running?

**Comment by jcran** [comment]
Looks like it ran out of memory. Do you have more than 8GB of memory in the machine, and have you configured (the underlying daemon of) Docker to allow access to that memory?  This is how we recommend Docker be configured: 
![image](https://user-images.githubusercontent.com/76854/95930663-aa610680-0d8c-11eb-8c13-7d2b81fed011.png) - and that any given instance of intrigue core be started with the ` --memory=8g` option

**Comment by jcran** [comment]
If you have any more issues, feel free to drop by the #core-help channel in https://join.slack.com/t/intrigue-community/shared_invite/zt-gh42ghi8-P~Z6wf1Bj5097vLLuqen6g

**Comment by JaderKb** [comment]
> I've had issues running with docker engine that came with distro, but was successful after installing from https://docs.docker.com/engine/install/ . What OS/Distro are you running?

actually I already found the problem.. I had to change the path where it was tryting to mounting..Intesad of /data...I put /tmp.. I believe that is something relatet to permission.

**Comment by jcran** [comment]
Okay thanks for reporting back. Feel free to jump into the channel, and let us know if you have any more issues!
