### ISSUE TITLE
Issues on Default Kali install on AMD64 + Docker 

### ISSUE THREAD

**Issue by physchosis** [intrigueio/intrigue-core#24]
Solution:
This probably just needs some good ole fashion TLC notes and all but I took fresh kali on AMD64 docker instance and ran through installation of redis etc etc on a docker instance. A note to add to the docs would be to run a gem update first or install the non kali packed ruby version. There also seems to be a bug in that puma is looking for ./config/puma.rb but only ./config/puma.rb.default exists no big deal just needs to be moved from puma.rb.default to puma.rb or add it to the readme...

The problem:
I ran into a few bundle errors. zlib and a bunch of other stuff were throwing errors..I don't think some of the libs were installed by default on kali so it required libgcrypt11-dev and zlib1g-dev along with a host of other libraries due to ruby gem libs being required and ended up getting bundle errors due to missing libraries etc etc, it basically ended up requiring a great deal of libs like the following....

sudo apt-get install build-essential libreadline-dev libssl-dev libpq5 libpq-dev libreadline5 libsqlite3-dev libpcap-dev openjdk-7-jre git-core autoconf postgresql pgadmin3 curl zlib1g-dev libxml2-dev libxslt1-dev vncviewer libyaml-dev curl zlib1g-dev

I didn't really want to do that because I wanted a default Kali installation for the docker instance to not mess with the libraries but I finally just decided to do a full gem update....

Then started formman start and obtained a puma error
root@8696ab6be916:~/intrigue-core#  foreman start
06:35:17 web.1    | started with pid 20596
06:35:17 worker.1 | started with pid 20597
06:35:19 web.1    | /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:20:in `read': No such file or directory @ rb_sysopen - ./config/puma.rb (Errno::ENOENT)
06:35:19 web.1    |     from /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:20:in`_load_from'
06:35:19 web.1    |     from /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:9:in `block in load'
06:35:19 web.1    |     from /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:8:in`tap'
06:35:19 web.1    |     from /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:8:in `load'
06:35:19 web.1    |     from /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/configuration.rb:56:in`load'
06:35:19 web.1    |     from /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/cli.rb:531:in `parse_options'
06:35:19 web.1    |     from /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/cli.rb:189:in`run'
06:35:19 web.1    |     from /var/lib/gems/2.1.0/gems/puma-2.13.4/bin/puma:10:in `<top (required)>'
06:35:19 web.1    |     from /usr/local/bin/puma:23:in`load'
06:35:19 web.1    |     from /usr/local/bin/puma:23:in `<main>'
06:35:19 web.1    | exited with code 1
06:35:19 system   | sending SIGTERM to all processes
06:35:19 worker.1 | terminated by SIGTERM
root@8696ab6be916:~/intrigue-core#

Original Installation errors from bundle errors were a list of things like the following...

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

```
/usr/bin/ruby2.1 extconf.rb
```

checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby2.1
    --help
    --clean
    --use-system-libraries
    --enable-static
    --disable-static
    --with-zlib-dir
    --without-zlib-dir
    --with-zlib-include
    --without-zlib-include=${zlib-dir}/include
    --with-zlib-lib
    --without-zlib-lib=${zlib-dir}/lib
    --enable-cross-build
    --disable-cross-build

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.6.2/gem_make.out
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.
root@8696ab6be916:~/intrigue-core# ruby -v
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
root@8696ab6be916:~/intrigue-core# cat /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.6.2/mkmf.log
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.1.0 -I/usr/include/ruby-2.1.0/ruby/backward -I/usr/include/ruby-2.1.0 -I. -D_FORTIFY_SOURCE=2   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC  conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-z,relro -L/build/ruby2.1-S44MX0/ruby2.1-2.1.5/debian/lib -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.1  -lpthread -lgmp -ldl -lcrypt -lm   -lc "

**Comment by jcran** [comment]
Copy the puma.rb.default to puma.rb and config.json.default to config.json
in the config folder.

On Thursday, September 10, 2015, physchosis <notifications@github.com>
wrote:

> Solution:
> This probably just needs some good ole fashion TLC notes and all but I
> took fresh kali on AMD64 docker instance and ran through installation of
> redis etc etc on a docker instance. A note to add to the docs would be to
> run a gem update first or install the non kali packed ruby version. There
> also seems to be a bug in that puma is looking for ./config/puma.rb but
> only ./config/puma.rb.default exists no big deal just needs to be moved
> from puma.rb.default to puma.rb or add it to the readme...
>
> The problem:
> I ran into a few bundle errors. zlib and a bunch of other stuff were
> throwing errors..I don't think some of the libs were installed by default
> on kali so it required libgcrypt11-dev and zlib1g-dev along with a host of
> other libraries due to ruby gem libs being required and ended up getting
> bundle errors due to missing libraries etc etc, it basically ended up
> requiring a great deal of libs like the following....
>
> sudo apt-get install build-essential libreadline-dev libssl-dev libpq5
> libpq-dev libreadline5 libsqlite3-dev libpcap-dev openjdk-7-jre git-core
> autoconf postgresql pgadmin3 curl zlib1g-dev libxml2-dev libxslt1-dev
> vncviewer libyaml-dev curl zlib1g-dev
>
> I didn't really want to do that because I wanted a default Kali
> installation for the docker instance to not mess with the libraries but I
> finally just decided to do a full gem update....
>
> Then started formman start and obtained a puma error
> root@8696ab6 <https://github.com/root/intrigue-core/commit/8696ab6be916>:~/intrigue-core#
> foreman start
> 06:35:17 web.1 | started with pid 20596
> 06:35:17 worker.1 | started with pid 20597
> 06:35:19 web.1 |
> /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:20:in read': No such
> file or directory @ rb_sysopen - ./config/puma.rb (Errno::ENOENT)
> 06:35:19 web.1 | from
> /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:20:in_load_from'
> 06:35:19 web.1 | from
> /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:9:in block in load'
> 06:35:19 web.1 | from
> /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:8:intap'
> 06:35:19 web.1 | from
> /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/dsl.rb:8:in load'
> 06:35:19 web.1 | from
> /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/configuration.rb:56:inload'
> 06:35:19 web.1 | from
> /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/cli.rb:531:in parse_options'
> 06:35:19 web.1 | from
> /var/lib/gems/2.1.0/gems/puma-2.13.4/lib/puma/cli.rb:189:inrun'
> 06:35:19 web.1 | from /var/lib/gems/2.1.0/gems/puma-2.13.4/bin/puma:10:in <top
> (required)>'
> 06:35:19 web.1 | from /usr/local/bin/puma:23:inload'
> 06:35:19 web.1 | from /usr/local/bin/puma:23:in `
> '
> 06:35:19 web.1 | exited with code 1
> 06:35:19 system | sending SIGTERM to all processes
> 06:35:19 worker.1 | terminated by SIGTERM
> root@8696ab6be916:~/intrigue-core#
>
> Original Installation errors from bundle errors were a list of things like
> the following...
>
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
>
> /usr/bin/ruby2.1 extconf.rb
>
> checking if the C compiler accepts ... yes
> Building nokogiri using packaged libraries.
> checking for gzdopen() in -lz... no
> zlib is missing; necessary for building libxml2
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers. Check the mkmf.log file for more details. You may
> need configuration options.
>
> Provided configuration options:
> --with-opt-dir
> --without-opt-dir
> --with-opt-include
> --without-opt-include=${opt-dir}/include
> --with-opt-lib
> --without-opt-lib=${opt-dir}/lib
> --with-make-prog
> --without-make-prog
> --srcdir=.
> --curdir
> --ruby=/usr/bin/ruby2.1
> --help
> --clean
> --use-system-libraries
> --enable-static
> --disable-static
> --with-zlib-dir
> --without-zlib-dir
> --with-zlib-include
> --without-zlib-include=${zlib-dir}/include
> --with-zlib-lib
> --without-zlib-lib=${zlib-dir}/lib
> --enable-cross-build
> --disable-cross-build
>
> extconf failed, exit code 1
>
> Gem files will remain installed in
> /var/lib/gems/2.1.0/gems/nokogiri-1.6.6.2 for inspection.
> Results logged to
> /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.6.2/gem_make.out
> An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot
> continue.
> Make sure that gem install nokogiri -v '1.6.6.2' succeeds before bundling.
> root@8696ab6 <https://github.com/root/intrigue-core/commit/8696ab6be916>:~/intrigue-core#
> ruby -v
> ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
> root@8696ab6 <https://github.com/root/intrigue-core/commit/8696ab6be916>:~/intrigue-core#
> cat
> /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/nokogiri-1.6.6.2/mkmf.log
> "gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.1.0
> -I/usr/include/ruby-2.1.0/ruby/backward -I/usr/include/ruby-2.1.0 -I.
> -D_FORTIFY_SOURCE=2 -g -O2 -fstack-protector-strong -Wformat
> -Werror=format-security -fPIC conftest.c -L. -L/usr/lib/x86_64-linux-gnu
> -L. -Wl,-z,relro -L/build/ruby2.1-S44MX0/ruby2.1-2.1.5/debian/lib
> -fstack-protector -rdynamic -Wl,-export-dynamic -lruby-2.1 -lpthread -lgmp
> -ldl -lcrypt -lm -lc "
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/intrigueio/intrigue-core/issues/24>.
>


-- 
Jonathan Cran
jcran@intrigue.io
http://www.intrigue.io

**Comment by jcran** [comment]
Just pushed a commit that gets rid of the default puma config at config/puma.rb.default in favor of just having the default config in config/puma.rb. (So that removes the need to copy config/puma.rb.default -> config/puma.rb). Additionally, there's no need to manually copy the config.json.default file, the app handles that on startup. 

Do a pull and 'foreman start' should just work. If it doesn't, let me know.

**Comment by jcran** [comment]
Sorry, just re-read and saw that you'd already figured that out. :+1: 

If you're still hitting gem compilation errors on Kali, let me know. I'll spin up an instance and do some testing. I'm planning to thin out the gem dependencies at some point in the near future before a GA release. 

Thanks for testing!!

**Comment by physchosis** [comment]
Here is what I ended up having to do (which could be turned into a dockerfile)

$apt-get update
$apt-get install build-essential
$apt-get install tcl8.5
$apt-get install bundler

# To get redis I added dotdeb.org's source list
In order to get in on this goodness you must first add the Dotdeb repositories to your APT sources. Create a new list file in /etc/apt/sources.list.d/ and fill it with the following content.

Add this to sources.list to fetch latest Redis or build your own

# /etc/apt/sources.list.d/dotdeb.org.list
deb http://packages.dotdeb.org squeeze all
deb-src http://packages.dotdeb.org squeeze all
Then you need to authenticate these repositories using their public key.

$wget -q -O - http://www.dotdeb.org/dotdeb.gpg | apt-key add -
And finally, update your APT cache and install Redis.

$ apt-get install redis-server

$ gem update

$ gem install nokogiri -v '1.6.6.2'

$ apt-get install libxml2

$ apt-get install zlib1g-dev

gem install puma -v '2.13.4'

$apt-get install build-essential libreadline-dev libssl-dev libpq5 libpq-dev libreadline5 libsqlite3-dev libpcap-dev openjdk-7-jre git-core autoconf postgresql pgadmin3 curl zlib1g-dev libxml2-dev libxslt1-dev vncviewer libyaml-dev curl zlib1g-dev

$ bundle install

$ foreman start....

**Comment by jcran** [comment]
Closing this out as the Docker setup is the preferred environment now.
