### ISSUE TITLE
docker install error on Raspberry Pi

### ISSUE THREAD

**Issue by RogueThread** [intrigueio/intrigue-core#276]
> docker run -e LANG=C.UTF-8 \
> --memory=8g \
> -p 0.0.0.0:7777:7777 \
> -it $IMAGE
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size

uname -a output
`
Linux 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
`

**Comment by JoeUser47** [comment]
It's an issue with docker & the kernel. When I ran into it on 64bit pc ubuntu 20.04 updating grub with
```GRUB_GFXPAYLOAD_LINUX="cgroup_enable=memory swapaccount1=1"```
fixed it for me, but I don't know on Pi. Saw some mentions here --> https://askubuntu.com/questions/1189480/raspberry-pi-4-ubuntu-19-10-cannot-enable-cgroup-memory-at-boostrap hope it helps.

**Comment by JoeUser47** [comment]
Does that pi have enough ram to give 8g to the docker image and still run host?

**Comment by RogueThread** [comment]
good call..
`free -h
>              total        used        free      shared  buff/cache   available
>Mem:          975Mi       151Mi       101Mi        30Mi       722Mi       760Mi
>Swap:            0B          0B          0B
`

**Comment by RogueThread** [comment]
Wouldn't reducing the --memory flag solve the issue?

Cmdline:
`docker run -e LANG=C.UTF-8 -v ~/intrigue-core-data:/tmp -p 0.0.0.0:7777:7777 --memory=4g -it intrigueio/intrigue-core`

Error:
`WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size`

**Comment by RogueThread** [comment]
Any releases coming soon to accomodate for armv7l processors?

**Comment by jcran** [comment]
we'd strongly recommend 8GB+.  IF you can accommodate that, then installing on an ubuntu 20.04 box should be a snap using these instructions: https://github.com/intrigueio/intrigue-core/wiki/Setting-up-a-Development-Environment-(on-Ubuntu,-Kali,-Debian)

Be aware it's not a super supported process, and there are likely to be a few roadbumps. If you're willing to work through them with us, jump in the slack channel and join #core-help, we'll assist.
