### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pentester** [intrigueio/intrigue-core#36]
Hi, I am trying to install intrigue-core on Ubuntu 16.04 beta but I got this error:

ddos@PenTester:/pentest/intelligence-gathering/core$ bundle exec rake migrate
Setup initiated!
Copying system config....
File exists: /pentest/intelligence-gathering/core/config/config.json
Copying database config....
File exists: /pentest/intelligence-gathering/core/config/database.yml
Copying sidekiq scan worker config....
File exists: /pentest/intelligence-gathering/core/config/sidekiq-scan.yml
Copying sidekiq task worker config....
File exists: /pentest/intelligence-gathering/core/config/sidekiq-task.yml
Obtaining geolocation database...
File exists: /pentest/intelligence-gathering/core/data/geolitecity/latest.dat
Fatal! Unable to read /pentest/intelligence-gathering/core/config/config.json
Error... Unable to migrate: unexpected return

**Comment by jcran** [comment]
Hey @pentester can you give it a try now?

**Comment by pentester** [comment]
New error:

foreman start
23:20:04 web.1         | started with pid 8853
23:20:04 task-worker.1 | started with pid 8854
23:20:04 scan-worker.1 | started with pid 8855
23:20:05 web.1         | Setting puma environment to: development
23:20:05 web.1         | Puma starting in single mode...
23:20:05 web.1         | * Version 3.1.0 (ruby 2.2.0-p0), codename: El Niño Winter Wonderland
23:20:05 web.1         | * Min threads: 0, max threads: 16
23:20:05 web.1         | * Environment: development
23:20:05 task-worker.1 | Permission denied @ rb_sysopen - /pentest/intelligence-gathering/intrigue-core/tmp/pids/intrigue-sidekiq-task.pid
23:20:05 task-worker.1 | /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:352:in `initialize'
23:20:05 task-worker.1 | /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:352:in `open'
23:20:05 task-worker.1 | /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:352:in `write_pid'
23:20:05 task-worker.1 | /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:42:in `parse'
23:20:05 task-worker.1 | /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sidekiq-4.1.1/bin/sidekiq:11:in `<top (required)>'
23:20:05 task-worker.1 | /home/ddos/.rvm/gems/ruby-2.2.0@core/bin/sidekiq:23:in `load'
23:20:05 task-worker.1 | /home/ddos/.rvm/gems/ruby-2.2.0@core/bin/sidekiq:23:in `<main>'
23:20:05 task-worker.1 | /home/ddos/.rvm/gems/ruby-2.2.0@core/bin/ruby_executable_hooks:15:in `eval'
23:20:05 task-worker.1 | /home/ddos/.rvm/gems/ruby-2.2.0@core/bin/ruby_executable_hooks:15:in `<main>'
23:20:05 task-worker.1 | exited with code 1
23:20:05 system        | sending SIGTERM to all processes
23:20:05 web.1         | ! Unable to load application: NoMethodError: undefined method `stop' for nil:NilClass
23:20:05 web.1         | /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/lib/puma/single.rb:16:in `stop': undefined method `stop' for nil:NilClass (NoMethodError)
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/lib/puma/launcher.rb:147:in `stop'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/lib/puma/launcher.rb:374:in `block in setup_signals'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:1800:in `call'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:1800:in `block (2 levels) in cleaned_caller'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:1800:in `any?'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:1800:in `block in cleaned_caller'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:1800:in `reject'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:1800:in `cleaned_caller'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:1493:in `caller_files'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:1778:in `inherited'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:1959:in `<module:Sinatra>'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/base.rb:16:in `<top (required)>'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/main.rb:1:in `require'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra/main.rb:1:in `<top (required)>'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra.rb:1:in `require'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/sinatra-1.4.7/lib/sinatra.rb:1:in `<top (required)>'
23:20:05 web.1         | 	from /pentest/intelligence-gathering/intrigue-core/core.rb:1:in `require'
23:20:05 web.1         | 	from /pentest/intelligence-gathering/intrigue-core/core.rb:1:in `<top (required)>'
23:20:05 web.1         | 	from config.ru:2:in `require'
23:20:05 web.1         | 	from config.ru:2:in `block in <main>'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
23:20:05 web.1         | 	from config.ru:in `new'
23:20:05 web.1         | 	from config.ru:in `<main>'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/lib/puma/configuration.rb:316:in `load_rackup'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/lib/puma/configuration.rb:245:in `app'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/lib/puma/runner.rb:119:in `load_and_bind'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/lib/puma/single.rb:84:in `run'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/lib/puma/launcher.rb:173:in `run'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/lib/puma/cli.rb:74:in `run'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/gems/puma-3.1.0/bin/puma:10:in `<top (required)>'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/bin/puma:23:in `load'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/bin/puma:23:in `<main>'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/bin/ruby_executable_hooks:15:in `eval'
23:20:05 web.1         | 	from /home/ddos/.rvm/gems/ruby-2.2.0@core/bin/ruby_executable_hooks:15:in `<main>'
23:20:05 web.1         | exited with code 1
23:20:05 scan-worker.1 | terminated by SIGTERM

**Comment by jcran** [comment]
are you running as root? It appears the daemon can't write to the directory in which it's been started

**Comment by jcran** [comment]
Closing this out due to inactivity.
