### ISSUE TITLE
Censys error when executing "foreman start"

### ISSUE THREAD

**Issue by metalkey** [intrigueio/intrigue-core#38]
I'm receiving the following error.

root@kali:~/kalifiles/scanners/intrigue-core# foreman start
11:39:47 web.1         | started with pid 26653
11:39:47 task-worker.1 | started with pid 26654
11:39:47 scan-worker.1 | started with pid 26655
11:39:50 web.1         | Setting puma environment to: development
11:39:50 web.1         | Puma starting in single mode...
11:39:50 web.1         | * Version 3.1.0 (ruby 2.1.5-p273), codename: El Niño Winter Wonderland
11:39:50 web.1         | * Min threads: 0, max threads: 16
11:39:50 web.1         | * Environment: development
11:39:52 scan-worker.1 | Intrigue-core system environment: development
11:39:52 task-worker.1 | Intrigue-core system environment: development
11:39:52 scan-worker.1 | 2016-03-15T00:39:52.261Z 26655 TID-6dl9g INFO: Booting Sidekiq 4.1.1 with redis options {:url=>"redis://localhost:6379/", :namespace=>"intrigue"}
11:39:52 task-worker.1 | 2016-03-15T00:39:52.276Z 26654 TID-2a9yk INFO: Booting Sidekiq 4.1.1 with redis options {:url=>"redis://localhost:6379/", :namespace=>"intrigue"}
11:39:52 web.1         | Intrigue-core system environment: development
11:39:54 scan-worker.1 | /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require': /var/lib/gems/2.1.0/bundler/gems/censys-83dab46e0534/lib/censys.rb:58: syntax error, unexpected ':', expecting => (SyntaxError)
11:39:54 scan-worker.1 |         "query": keyword
11:39:54 scan-worker.1 |                 ^
11:39:54 scan-worker.1 | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
11:39:54 scan-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/tasks/search_censys.rb:1:in `<top (required)>'
11:39:54 scan-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `require_relative'
11:39:54 scan-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `block in <top (required)>'
11:39:54 scan-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `each'
11:39:54 scan-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `<top (required)>'
11:39:54 scan-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/core.rb:132:in `require_relative'
11:39:54 scan-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/core.rb:132:in `<top (required)>'
11:39:54 scan-worker.1 | 	from /var/lib/gems/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:237:in `require'
11:39:54 scan-worker.1 | 	from /var/lib/gems/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:237:in `boot_system'
11:39:54 scan-worker.1 | 	from /var/lib/gems/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:49:in `run'
11:39:54 scan-worker.1 | 	from /var/lib/gems/2.1.0/gems/sidekiq-4.1.1/bin/sidekiq:12:in `<top (required)>'
11:39:54 scan-worker.1 | 	from /usr/local/bin/sidekiq:23:in `load'
11:39:54 scan-worker.1 | 	from /usr/local/bin/sidekiq:23:in `<main>'
11:39:54 task-worker.1 | /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require': /var/lib/gems/2.1.0/bundler/gems/censys-83dab46e0534/lib/censys.rb:58: syntax error, unexpected ':', expecting => (SyntaxError)
11:39:54 task-worker.1 |         "query": keyword
11:39:54 task-worker.1 |                 ^
11:39:54 task-worker.1 | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
11:39:54 task-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/tasks/search_censys.rb:1:in `<top (required)>'
11:39:54 task-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `require_relative'
11:39:54 task-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `block in <top (required)>'
11:39:54 task-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `each'
11:39:54 task-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `<top (required)>'
11:39:54 task-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/core.rb:132:in `require_relative'
11:39:54 task-worker.1 | 	from /root/kalifiles/scanners/intrigue-core/core.rb:132:in `<top (required)>'
11:39:54 task-worker.1 | 	from /var/lib/gems/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:237:in `require'
11:39:54 task-worker.1 | 	from /var/lib/gems/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:237:in `boot_system'
11:39:54 task-worker.1 | 	from /var/lib/gems/2.1.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:49:in `run'
11:39:54 task-worker.1 | 	from /var/lib/gems/2.1.0/gems/sidekiq-4.1.1/bin/sidekiq:12:in `<top (required)>'
11:39:54 task-worker.1 | 	from /usr/local/bin/sidekiq:23:in `load'
11:39:54 task-worker.1 | 	from /usr/local/bin/sidekiq:23:in `<main>'
11:39:54 task-worker.1 | exited with code 1
11:39:54 system        | sending SIGTERM to all processes
11:39:54 scan-worker.1 | exited with code 1
11:39:54 web.1         | ! Unable to load application: NoMethodError: undefined method `stop' for nil:NilClass
11:39:54 web.1         | /var/lib/gems/2.1.0/gems/puma-3.1.0/lib/puma/single.rb:16:in `stop': undefined method `stop' for nil:NilClass (NoMethodError)
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/puma-3.1.0/lib/puma/launcher.rb:147:in `stop'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/puma-3.1.0/lib/puma/launcher.rb:374:in `block in setup_signals'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `call'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:2:in `<top (required)>'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail.rb:68:in `<module:Mail>'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/mail-2.6.3/lib/mail.rb:2:in `<top (required)>'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/gmail-0.6.0/lib/gmail.rb:3:in `<top (required)>'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
11:39:54 web.1         | 	from /root/kalifiles/scanners/intrigue-core/lib/tasks/email_bounceback.rb:1:in `<top (required)>'
11:39:54 web.1         | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `require_relative'
11:39:54 web.1         | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `block in <top (required)>'
11:39:54 web.1         | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `each'
11:39:54 web.1         | 	from /root/kalifiles/scanners/intrigue-core/lib/all.rb:20:in `<top (required)>'
11:39:54 web.1         | 	from /root/kalifiles/scanners/intrigue-core/core.rb:132:in `require_relative'
11:39:54 web.1         | 	from /root/kalifiles/scanners/intrigue-core/core.rb:132:in `<top (required)>'
11:39:54 web.1         | 	from config.ru:2:in `require'
11:39:54 web.1         | 	from config.ru:2:in `block in <main>'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
11:39:54 web.1         | 	from config.ru:in `new'
11:39:54 web.1         | 	from config.ru:in `<main>'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/puma-3.1.0/lib/puma/configuration.rb:316:in `load_rackup'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/puma-3.1.0/lib/puma/configuration.rb:245:in `app'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/puma-3.1.0/lib/puma/runner.rb:119:in `load_and_bind'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/puma-3.1.0/lib/puma/single.rb:84:in `run'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/puma-3.1.0/lib/puma/launcher.rb:173:in `run'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/puma-3.1.0/lib/puma/cli.rb:74:in `run'
11:39:54 web.1         | 	from /var/lib/gems/2.1.0/gems/puma-3.1.0/bin/puma:10:in `<top (required)>'
11:39:54 web.1         | 	from /usr/local/bin/puma:23:in `load'
11:39:54 web.1         | 	from /usr/local/bin/puma:23:in `<main>'
11:39:54 web.1         | exited with code 1

**Comment by jcran** [comment]
Looks like this might be a ruby version issue. Pulling down a copy of Kali and testing.

**Comment by YouGina** [comment]
In case it helps, changing the line 58 of censys.rb worked for me:
`"query": keyword`
to
`:query => keyword`

**Comment by jcran** [comment]
Ah should have been a ruby hash since it's later converted to json. Addressed upstream: https://github.com/pentestify/censys/commit/da58c6fee0f0dc944d849fcf41552cd2f4cbcfde
