### ISSUE TITLE
typo in ubuntu docs : sudo apt-get -y install  redis-sever

### ISSUE THREAD

**Issue by vmalguy** [intrigueio/intrigue-core#43]
from https://github.com/intrigueio/intrigue-core/wiki/Setting-up-a-Test-Environment-on-Ubuntu-Linux 

`sudo apt-get -y install  redis-sever
E: Unable to locate package redis-sever`

`sudo apt-get -y install redis-server
Much better :)`

**Comment by jcran** [comment]
hah, thanks for catching that, never a good idea to sever things. saw you
edited the wiki, closing this out.

On Tue, May 24, 2016 at 8:05 AM, vmalguy <notifications@github.com> wrote:

> from
> https://github.com/intrigueio/intrigue-core/wiki/Setting-up-a-Test-Environment-on-Ubuntu-Linux
>
> sudo apt-get -y install redis-sever
> E: Unable to locate package redis-sever
>
> sudo apt-get -y install redis-server
> Much better :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/intrigueio/intrigue-core/issues/43>
>



-- 
Jonathan Cran
jcran@intrigue.io
http://www.intrigue.io
