### ISSUE TITLE
Can not build docker build

### ISSUE THREAD

**Issue by turbologistik** [intrigueio/intrigue-core#63]
I try build docker image, can you help me?

And 11 step faild

Step 11/41 : RUN make -j 3 && make install
 ---> Running in 8698c13cd544
clang -g -ggdb    -Wall -O3 -c src/crypto-base64.c -o tmp/crypto-base64.o
make: clang: Command not found
clang -g -ggdb    -Wall -O3 -c src/crypto-blackrock2.c -o tmp/crypto-blackrock2.o
Makefile:87: recipe for target 'tmp/crypto-base64.o' failed
Makefile:87: recipe for target 'tmp/crypto-blackrock2.o' failed
make: clang: Command not found
make: *** [tmp/crypto-base64.o] Error 127
make: *** Waiting for unfinished jobs....
make: *** [tmp/crypto-blackrock2.o] Error 127

My config:
Ubunta
Docker version:      17.06.0-ce

**Comment by KINGSABRI** [comment]
Same here! 
Quick fix: 
I added `clang` to the `apt install` line in docker file `Dockerfile` then I ran `docker build .` again 

I believe it should be there without modifications. 

HTH

**Comment by jcran** [comment]
Thanks for the report and thanks for the fix @KINGSABRI! Pushed to develop branch.
