### ISSUE TITLE
Fix Vagrantfile - randomized password

### ISSUE THREAD

**Issue by jcran** [intrigueio/intrigue-core#69]
When starting the application with Vagrant, the password is not randomly generated. 

```
the app is available at http://10.0.0.10:9292/, which I got from VagrantFile
also the generated password doesn't work
I logged in with password from config.json
```

**Comment by mrunc** [comment]
I also tried vagrant on macOS 10.13.4 VirtualBox 5.2.10 and I can't access the app on host with 127.0.0.1:7777 
The port forward for ssh 22/2222 is working on host but not 7777
from ssh on guest I can access the app with lynx http://127.0.0.1:7777 with no problem

**Comment by jcran** [comment]
@mrunc the system's services weren't starting automatically since the underlying box moved to 16.04. Standby, fixing & adding instructions.

**Comment by jcran** [comment]
Believe this has been addressed by improving the setup process in the bootstrap shell script, please re-open if it persists.
