### ISSUE TITLE
Docker build errors

### ISSUE THREAD

**Issue by DemanNL** [intrigueio/intrigue-core#74]
Hi,

After building I try "docker run -ti -p 7777:7777 9cb040aeecee" but intrigue never starts. This is the output:
```
root@kali:~/Tools/intrigue-core# docker run -ti -p 7777:7777 9cb040aeecee
 * Starting PostgreSQL 9.6 database server                               [ OK ] 
Starting redis-server: redis-server.
Starting intrigue-core processes
[+] Setup initiated!
[+] Copying puma config....
[ ] File already exists, skipping: /core/config/puma.rb
[+] Copying system config....
[+] Creating system config: /core/config/config.json
[+] GENERATING NEW SYSTEM PASSWORD!
[+]
[+] SYSTEM PASSWORD: jrgfqbxfxjb
[+]
[+] Copying database config....
[+] Creating.... /core/config/database.yml
[+] Copying redis config....
[+] Creating.... /core/config/redis.yml
[+] Setting up sidekiq config....
[+] Copying: /core/config/sidekiq.yml.default
[+] Downloading latest data files...
[+] Getting latest MaxMind GeoLiteCity database
[+] Getting latest web_accounts_list.json
[+] Getting latest ipv4-address-space.csv
[+] Getting latest ASN data from APNIC
[+] Copying control script...
[ ] File already exists, skipping: /core/util/control.sh
[+] Complete!
[+] Schema Version: 27
Starting task processing... 1
Starting puma...
root@kali:~/Tools/intrigue-core#
```

Now during build I get the following red text errors:
```
debconf: delaying package configuration, since apt-utils is not installed
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Ver Cluster Port Status Owner    Data directory               Log file
9.6 main    5432 down   postgres /var/lib/postgresql/9.6/main /var/log/postgresql/postgresql-9.6-main.log
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
src/proto-ntlmssp.c: In function 'ntlmssp_decode':
src/proto-ntlmssp.c:114:14: warning: variable 'flags' set but not used [-Wunused-but-set-variable]
     unsigned flags;
              ^
mesg: ttyname failed: Inappropriate ioctl for device
```

This is my docker version:
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:13 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:27 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Comment by jcran** [comment]
Dockerfile's been updated & cleaned up, and you can now pull directly from dockerhub. Re-open if that doesn't resolve the issue. https://hub.docker.com/r/intrigueio/intrigue-core/

**Comment by imrantvlk** [comment]
I pulled the image from dockerhub but it fails when downloading large data file:

`[+] Restarting Postgres...
 * Restarting PostgreSQL 9.6 database server                                                                                                                                                             [ OK ] 
[+] Restarting Redis...
Stopping redis-server: redis-server.
Starting redis-server: redis-server.
[+] Restarting Intrigue...
Starting intrigue-core processes
[+] Setup initiated!
[+] Copying puma config....
[ ] File already exists, skipping: /core/config/puma.rb
[+] Copying system config....
[+] Creating system config: /core/config/config.json
[+] GENERATING NEW SYSTEM PASSWORD!
[+]
[+] SYSTEM PASSWORD: kuknwwztiwz
[+]
[+] Copying database config....
[ ] File already exists, skipping: /core/config/database.yml
[+] Copying redis config....
[ ] File already exists, skipping: /core/config/redis.yml
[+] Setting up sidekiq config....
[+] /core/config/sidekiq.yml already exists!
[+] Downloading latest data files...
gzip: GeoLiteCity.dat.gz: No such file or directory
mv: cannot stat 'GeoLiteCity.dat': No such file or directory`

Any idea what I should do?

**Comment by jcran** [comment]
I'll be pushing up a new image shortly that addresses this issue. 

Also - in the future be sure to open a new ticket, as I did not see this for a few days. 

Thanks for trying it out, and I'll respond as soon as the image is available to pull. 

jcran

**Comment by jcran** [comment]
Good to test. Make sure to expose port 7777, ala:
```$ docker run -i -t -p 0.0.0.0:7777:7777 [image id]```
