### ISSUE TITLE
NoMethodError at /test/analysis/systems undefined method 'match' 

### ISSUE THREAD

**Issue by tempaccount-13** [intrigueio/intrigue-core#76]
Hello,

After installing intrigue using vagrant and messing around a bit I got the following error when clicking on 'systems' under the 'analysis' menu:
> NoMethodError at /test/analysis/systems
> undefined method `match' for {"name"=>"Oracle Virtualbox", "accuracy"=>100}:Hash
> /core/app/routes/analysis.rb in block (2 levels) in <class:IntrigueApp>
>           os_string = e.get_detail("os").to_a.first.match(/(.*)(\ \(.*\))/)[1]
> /core/app/routes/analysis.rb in each
>       @entities.each do |e|
> /core/app/routes/analysis.rb in block in <class:IntrigueApp>
>       @entities.each do |e|

For some reason it tries to do a regex match on a Hash object, which is not supported in Ruby(to my knowledge). I used shodan and nmap on the microsoft domain described in the tutorial on the intrigue.io website, example in attachment. I am not a ruby expert, so I don't know why this happens, maybe to_a.first should be done recursively until a primitive object occurs?
Hope you can help me.

Best regards,

Henk

[test.entities.json.txt](https://github.com/intrigueio/intrigue-core/files/2183520/test.entities.json.txt)

**Comment by jcran** [comment]
This has been resolved, thanks for the report Henk
