### ISSUE TITLE
Ability to import a list

### ISSUE THREAD

**Issue by HollywoodMarks** [intrigueio/intrigue-core#77]
It would be great to be able to import a list, whether that's domains, IP's, or Netblocks.  For example, when I want to create a task to "Create Entity" Entity Name does not allow more than entry.  If there was an import ability, or if the Entity Name could be a comma separated list that would work too.

**Comment by jcran** [comment]
Solid request, I could use this too, will work on it. Note that you can do this now via API or CLI. Example via CLI (after starting the service):  

```
### bundle exec ./core-cli.rb start [project_name] [task_name] DnsRecord#intrigue.io [depth] [options (a=b,c=d,...)] [handlers (csv,json,...)] [strategy_name]

bundle exec ./core-cli.rb start new_project create_entity DnsRecord#example.com 3 nil nil org_asset_discovery_active
```

**Comment by jcran** [comment]
Available now on master/develop branches, just added a (very hacky) ability to upload a file underneath a project at the following uri: http://localhost:7777/[project_name]/start/multiple

The file should be formatted like the following - EntityType#EntityName, 1 per line. 

Example:  
[DnsRecord#test.com
DnsRecord#test2.com
IpAddress#1.1.1.1

I'll think more deeply about this and add robust error checking later, but wanted to get something out there. Let me know if this doesn't work for you.

**Comment by jcran** [comment]
![image](https://user-images.githubusercontent.com/76854/45655730-58632f00-baa7-11e8-87f2-a71b7a1d1dbd.png)

**Comment by jcran** [comment]
This has been moved to /[project_name]/start/upload and is now linked in the navbar (see screenie below) 

![image](https://user-images.githubusercontent.com/76854/45691829-fa722e00-bb1e-11e8-88ba-f992a987eab5.png)

**Comment by jcran** [comment]
Marking this complete / closed.
