### ISSUE TITLE
problem in /core/lib/tasks/uri_brute_focused prevent intrigue from starting

### ISSUE THREAD

**Issue by th3g3nt3lman1** [intrigueio/intrigue-core#91]
/core/lib/all.rb:73:in `require_relative': /core/lib/tasks/uri_brute_focused_content.rb:76: syntax error, unexpected {, expecting ']' (SyntaxError)
      { path: "/.env", severity: 1, ...
      ^
/core/lib/tasks/uri_brute_focused_content.rb:76: syntax error, unexpected ',', expecting keyword_end
...PP_ENV/, status: "confirmed" },

**Comment by jcran** [comment]
Shit sorry about that. Fixed now with a merge from develop.
