### ISSUE TITLE
Unable to configure the API keys / Error when clicking on configure

### ISSUE THREAD

**Issue by th3g3nt3lman1** [intrigueio/intrigue-core#93]
tested with dockerhub version on ubuntu & debian, error appears :

NoMethodError at /system/config
undefined method `created_at' for nil:NilClass

    file: config.erb location: block in singleton class line: 3

**Comment by jcran** [comment]
awesome good catch, will have a fix up momentarily.

**Comment by jcran** [comment]
fixed by the commit above, give the dockerhub auto-build thing 20 mins or so to spin up a new rev
