### ISSUE TITLE
[enhancement]

### ISSUE THREAD

**Issue by Chad0ps** [intrigueio/intrigue-core#98]
check out [spyse](https://spyse.com). probably it can speed up the discovering. i think you will find it useful.

**Comment by jcran** [comment]
>> All information provided by Spyse services is constantly collected exclusively from public sources. Services provide both the latest information about domains and IP addresses on the Internet, as well as historical data.

Any idea what these sources are?

**Comment by jcran** [comment]
(and am i correct in assuming this is your tool / service?)

**Comment by Chad0ps** [comment]
> (and am i correct in assuming this is your tool / service?)

yeah, i'm just a part of the team. And we are using bunch of different services for each search type. For example, if we need to find open ports we are automatically validating the output with the help of 5 different tools. I can provide you with the full list if you need
